// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvMQCOpSUQGhQtPdGW55YSuhQIy7PDPI',
    appId: '1:779395263234:web:6bb13ac361844077c3701b',
    messagingSenderId: '779395263234',
    projectId: 'ku-attendance',
    authDomain: 'ku-attendance.firebaseapp.com',
    storageBucket: 'ku-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn5S2D-q7O4JJrO1xZR1ogr1XM3c3rtmI',
    appId: '1:779395263234:android:461909e55b3cd84bc3701b',
    messagingSenderId: '779395263234',
    projectId: 'ku-attendance',
    storageBucket: 'ku-attendance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-B6D1YHWvxwGBDw4FSCMmYid0RmioSVA',
    appId: '1:779395263234:ios:03d079a91ead8470c3701b',
    messagingSenderId: '779395263234',
    projectId: 'ku-attendance',
    storageBucket: 'ku-attendance.firebasestorage.app',
    iosBundleId: 'com.example.amIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJvMQCOpSUQGhQtPdGW55YSuhQIy7PDPI',
    appId: '1:779395263234:web:bb902d4362074a93c3701b',
    messagingSenderId: '779395263234',
    projectId: 'ku-attendance',
    authDomain: 'ku-attendance.firebaseapp.com',
    storageBucket: 'ku-attendance.firebasestorage.app',
  );
}
